application:
  subdomain: airylark
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://airylark:3000/
services:
  airylark:
    # upstream: wizdy/airylark:latest
    image: wizdy/airylark:latest
    user: root
    environment:
      - NODE_ENV=production
    binds:
      - /lzcapp/var/data:/app/data
    command: /lzcapp/pkg/content/startup.sh
