application:
  subdomain: airylark
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://airylark:3000/
services:
  airylark:
    # upstream: wizdy/airylark:latest@sha256:42ae6bdfa594034a909702c34ec88f52e6f12b4b80fa4aa4723237589e9c24b4
    image: registry.lazycat.cloud/czyt/wizdy/airylark:831672abda2c1d41
    user: root
    environment:
      - NODE_ENV=production
    binds:
      - /lzcapp/var/data:/app/data
    command: /lzcapp/pkg/content/startup.sh
