lzc-sdk-version: "0.1"
name: AiryLark
package: cloud.lazycat.app.airylark
version: 0.0.2
description: 一个多功能文档处理与翻译工具
homepage: https://github.com/wizd/airylark
author: wizd
application:
  subdomain: airylark
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://airylark:3000/
services:
  airylark:
    image: docker.hlmirror.com/wizdy/airylark:latest
    user: root
    environment:
      - NODE_ENV=production
    binds:
      - /lzcapp/var/data:/app/data
    command: /lzcapp/pkg/content/startup.sh 

